{{- if .Values.postgres.enabled }}
{{- $secretName := printf "%s-postgres" .Release.Name }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $customSecretName := .Values.postgres.auth.existingSecret }}
{{- $isCustomSecret := and $customSecretName (ne $customSecretName $secretName) }}
{{- $customSecret := "" }}
{{- if $isCustomSecret }}
  {{- $customSecret = lookup "v1" "Secret" .Release.Namespace $customSecretName }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ldap-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $existingSecret }}
  # Reuse existing password from previous installation
  postgres-password: {{ index $existingSecret.data "postgres-password" }}
  {{- else if and $isCustomSecret $customSecret }}
  # Use password from user-provided secret
  postgres-password: {{ index $customSecret.data "postgres-password" | default (index $customSecret.data "password") }}
  {{- else }}
  # Generate a new random password
  postgres-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
