{{- if .Values.postgres.enabled }}
{{- $secretName := printf "%s-postgres-credentials" (include "ldap-sync.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "ldap-sync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $existingSecret }}
  # Reuse existing password from previous installation
  password: {{ index $existingSecret.data "password" }}
  {{- else if .Values.postgres.auth.existingSecret }}
  # Use password from user-provided secret
  password: {{ (lookup "v1" "Secret" .Release.Namespace .Values.postgres.auth.existingSecret).data.password }}
  {{- else }}
  # Generate a new random password
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
